Repository pharmaverse/sdtmchecks, pull requests merged in 2023-08, with the labels that each got.

#199 Lyw unit tests
  tests/testthat/test-check_dm_actarm_arm.R
  tests/testthat/test-check_dm_age_missing.R
  tests/testthat/test-check_dm_dthfl_dthdtc.R
  tests/testthat/test-check_dm_usubjid_ae_usubjid.R
  tests/testthat/test-check_ds_ae_discon.R
  tests/testthat/test-check_ds_dsdecod_death.R
  tests/testthat/test-check_ds_dsdecod_dsstdtc.R
  tests/testthat/test-check_ds_dsscat.R
  tests/testthat/test-check_ds_dsterm_death_due_to.R
Labels: dev

#226 225 remove addin
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/addins.R
  README.Rmd
  README.md
  inst/rstudio/addins.dcf
  man/sdtmchecksSearch.Rd
  vignettes/faqs.Rmd
  vignettes/sdtmchecks.Rmd
  vignettes/write_a_check.Rmd
Labels: bug, dev

#238 remove excessive information about devtools::install_github
  README.Rmd
  README.md
Labels: documentation

#223 add some details about renv, style of fail, unit testing to write_a_check
  vignettes/write_a_check.Rmd
Labels: documentation
